dependencies:
  - role: common
    vars:
      user_groups: sudo,video,input,dialout,i2c
      install_repos:
        - name: google
          uris: "http://dl.google.com/linux/chrome/deb"
          signed_by: https://dl.google.com/linux/linux_signing_key.pub
      install_packages:
        - git
        - zsh
        - vim
        - tmux
        - default-jdk
        - ruby
        - xorg
        - i3
        - xbindkeys
        - xsel
        - hsetroot
        - numlockx
        - xcompmgr
        - redshift
        - ddcutil
        - brightnessctl
        - rxvt-unicode
        - chromium-browser
        - google-chrome-stable
        - ansible
        - alsa
        - pm-utils
        - pulseaudio
        - pulseaudio-module-bluetooth
        - pulsemixer
        - mplayer
        - npm
        - virtualbox
        - vagrant
        - flameshot
        - dbus-x11
        - libnotify-bin
        - solaar
        - weechat
        - weechat-headless
      user_files:
        - src: ssh/id_rsa
          dest: /home/scott/.ssh/
          mode: "0600"
        - src: ssh/known_hosts
          dest: /home/scott/.ssh/
          mode: "0644"
        - src: ssh/authorized_keys
          dest: /home/scott/.ssh/
          mode: "0600"
        - src: ssh/mainkeypair.pem
          dest: /home/scott/.ssh/
          mode: "0600"
        - src: aws/credentials
          dest: /home/scott/.aws/
          mode: "0664"
      system_files:
        - src: sudoers/power-control
          dest: /etc/sudoers.d/
          mode: "0440"
        - src: sudoers/solaar
          dest: /etc/sudoers.d/
          mode: "0440"
