dependencies:
  - role: common
    vars:
      user_groups: sudo,docker,video,input
      install_packages:
        - git
        - zsh
        - vim
        - docker.io
        - tmux
        - default-jdk
        - ruby
        - xorg
        - i3
        - xbindkeys
        - xsel
        - xcompmgr
        - brightnessctl
        - rxvt-unicode
        - chromium-browser
        - ansible
        - alsa
        - pulseaudio
        - pulseaudio-module-bluetooth
        - npm
        - vagrant
        - flameshot
        - dbus-x11
        - libnotify-bin
        - awscli
      user_files:
        - src: ssh/id_rsa
          dest: /home/scott/.ssh/
          mode: "0600"
        - src: ssh/known_hosts
          dest: /home/scott/.ssh/
          mode: "0644"
        - src: ssh/mainkeypair.pem
          dest: /home/scott/.ssh/
          mode: "0600"
        - src: aws/credentials
          dest: /home/scott/.aws/
          mode: "0664"
