---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
      environment: env

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-15.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[lxmx_oh_my_zsh::default]
      - recipe[machine-setup::default]
      # TODO: This overwrites idea64.vmoptions after install and I don't like that
      - recipe[idea::default]
    attributes:
