- hosts: all
  become: yes
  #sudo: yes
  #remote_user: root
  roles:
    - desktop
  gather_facts: true
  pre_tasks:
    - name: Install acl package (needed for permission controls)
      package:
        name: "acl"
