- hosts: all
  become: yes
  #sudo: yes
  #remote_user: root
  roles:
    - server
    - home-assistant-server
  gather_facts: no
  pre_tasks:
    - name: Update apt
      raw: apt update ; apt update
    - name: Install python2 (needed for ansible) and acl for timezone setup
      raw: apt install -y python3 acl

  tasks:
  # Necessary because we turn it off for python install pre_task
  - name: Gathering facts
    setup:
