- hosts: all
  become: yes
  #sudo: yes
  #remote_user: root
  gather_facts: no
  pre_tasks:
    - name: Update apt
      raw: apt update ; apt update
    - name: Install python2 (needed for ansible) and acl for timezone setup
      raw: apt install -y python acl

  tasks:
  # Necessary because we turn it off for python install pre_task
  - name: Gathering facts
    setup:

  - name: Import system setup tasks
    import_tasks: tasks/system-setup-tasks.yml

  - name: Import package install tasks
    import_tasks: tasks/package-install-tasks.yml

  - name: Setup users
    user:
      name: scott
      groups: sudo,docker
      shell: /bin/zsh

  - name: Create home bin dir
    become: yes
    become_user: scott
    file:
      path: ~/bin
      state: directory

  - name: Copy scottg489@gmail.com id_rsa to scott .ssh
    become: yes
    become_user: scott
    copy:
      src: ssh/id_rsa
      dest: /home/scott/.ssh/  # Trailing slash needed to create dirs if they don't exist
      owner: scott
      group: scott
      mode: 0600

  - name: Copy scottg489@gmail.com aws mainkeypair to scott .ssh
    become: yes
    become_user: scott
    copy:
      src: ssh/mainkeypair.pem
      dest: /home/scott/.ssh/  # Trailing slash needed to create dirs if they don't exist
      owner: scott
      group: scott
      mode: 0600
      
  - name: Copy known_hosts to scott .ssh
    become: yes
    become_user: scott
    copy:
      src: ssh/known_hosts
      dest: /home/scott/.ssh/  # Trailing slash needed to create dirs if they don't exist
      owner: scott
      group: scott
      mode: 0644

  - name: Copy scottg489@gmail.com aws credentials to scott .aws
    become: yes
    become_user: scott
    copy:
      src: aws/credentials
      dest: /home/scott/.aws/  # Trailing slash needed to create dirs if they don't exist
      owner: scott
      group: scott
      mode: 0664


  - name: Install imgur upload tool
    become: yes
    become_user: scott
    get_url:
      url: https://raw.githubusercontent.com/tremby/imgur.sh/main/imgur.sh
      dest: ~/bin/imgur
      mode: '0775'

  - name: Install xrectsel tool
    become: yes
    become_user: scott
    copy:
      src: bin/xrectsel/xrectsel
      dest: ~/bin/
      owner: scott
      group: scott
      mode: '0775'

  - name: Install oh-my-zsh
    become: yes
    become_user: scott
    # Reading in 'y' is necessary otherwise provisioning freezes. This is because the install script prompts 'y/n' at one point.
    shell: |
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" << EOF
      y
      EOF
    args:
      chdir: /home/scott/
      creates: ~/.oh-my-zsh

  - name: Import vim plugin tasks
    import_tasks: tasks/vim-plugin-tasks.yml

  - name: Clone tmux package manager (tpm)
    become: yes
    become_user: scott
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm

  - name: Import dotfile setup tasks
    import_tasks: tasks/dotfile-setup-tasks.yml
