- hosts: all
  become: yes
  #sudo: yes
  #remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2 (needed for ansible)'
      raw: apt install -y python acl

  tasks:
  # Necessary because we turn it off for python install pre_task
  - name: Gathering facts
    setup:

  - name: Include system setup tasks
    import_tasks: system-setup-tasks.yml

  - name: Include package install tasks
    import_tasks: package-install-tasks.yml

  - name: Copy scottg489@gmail.com id_rsa to scott .ssh
    become: yes
    become_user: scott
    copy:
      src: ssh/id_rsa
      dest: /home/scott/.ssh/  # Trailing slash needed to create dirs if they don't exist
      owner: scott
      group: scott
      mode: 0600

  - name: Copy known_hosts to scott .ssh
    become: yes
    become_user: scott
    copy:
      src: ssh/known_hosts
      dest: /home/scott/.ssh/  # Trailing slash needed to create dirs if they don't exist
      owner: scott
      group: scott
      mode: 0644

  - name: Include vim plugin tasks
    import_tasks: vim-plugin-tasks.yml

  - name: Clone tmux package manager (tpm)
    become: yes
    become_user: scott
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm

  - name: Import dotfile setup tasks
    import_tasks: dotfile-setup-tasks.yml
