name 'machine-setup'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures machine-setup'
long_description 'Installs/Configures machine-setup'
version '0.1.0'

depends 'apt', '~> 2.9.2'
depends 'lxmx_oh_my_zsh', '~> 0.5.0'
depends 'idea', '~> 0.4.0'
depends 'system', '~> 0.10.1'
