- name: Import master playbook
  import_playbook: master-playbook.yml

- hosts: all
  tasks:
  - name: Install packages
    package:
      name:
        - virtualbox-guest-utils
        - virtualbox-guest-x11
        - virtualbox-guest-dkms

