- name: Import package install tasks
  import_tasks: package-install-tasks.yml

- name: Import user setup tasks
  import_tasks: user-setup-tasks.yml

- name: Import system setup tasks
  import_tasks: system-setup-tasks.yml
