- name: Install packages required to install terraform (i.e. unzip)
  package:
    name:
      - unzip

- name: Install snap packages
  snap:
    classic: yes
    name:
      - intellij-idea-ultimate
      - webstorm

# TODO: Not working
#- name: Install gem packages
#  gem:
#    name: tmuxinator

- name: Install terraform
  shell: |
    curl https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip -o /tmp/terraform.zip && \
    unzip -d /usr/local/bin /tmp/terraform.zip && \
    rm /tmp/terraform.zip
  args:
    creates: /usr/local/bin/terraform

- name: Install Steam
  shell: |
    wget --output-document /tmp/steam.deb https://steamcdn-a.akamaihd.net/client/installer/steam.deb && \
    dpkg --install /tmp/steam.deb && \
    rm /tmp/steam.deb
  args:
    creates: /bin/steam

# Note: This is needed because xterm will be used as the default otherwise
- name: Use urxvt as the default terminal
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/urxvt
