- name: Install packages required to install terraform (i.e. unzip)
  package:
    name:
      - unzip

- name: Install snap packages
  snap:
    classic: yes
    channel: 2021.1/stable
    name:
      - intellij-idea-ultimate

- name: Import the Docker signing key (apt-key)
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Install Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: Install docker packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add user to docker group
  user:
    name: scott
    groups: "docker"
    append: yes
    shell: /bin/zsh

- name: Install terraform
  shell: |
    curl https://releases.hashicorp.com/terraform/0.14.0/terraform_0.14.0_linux_amd64.zip -o /tmp/terraform.zip && \
    unzip -d /usr/local/bin /tmp/terraform.zip && \
    rm /tmp/terraform.zip
  args:
    creates: /usr/local/bin/terraform

- name: Install Steam
  shell: |
    wget --output-document /tmp/steam.deb https://steamcdn-a.akamaihd.net/client/installer/steam.deb && \
    apt install -y /tmp/steam.deb && \
    rm /tmp/steam.deb
  args:
    creates: /bin/steam

# Note: This is needed because xterm will be used as the default otherwise
- name: Use urxvt as the default terminal
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/urxvt
