- name: Set timezone to US/Eastern
  timezone:
    name: US/Eastern

- name: Copy file to set inotify watch limit to be higher (for intellij)
  copy:
    src: sysctl.d/60-jetbrains.conf
    dest: /etc/sysctl.d/
    owner: root
    group: root
    mode: 0644
