- name: Install imgur upload tool
  become: yes
  become_user: scott
  get_url:
    url: https://raw.githubusercontent.com/tremby/imgur.sh/main/imgur.sh
    dest: ~/bin/imgur
    mode: '0775'

- name: Install xrectsel tool
  become: yes
  become_user: scott
  copy:
    src: bin/xrectsel/xrectsel
    dest: ~/bin/
    owner: scott
    group: scott
    mode: '0775'
