- name: Run all tasks as user
  block:
    - name: Install imgur upload tool
      get_url:
        url: https://raw.githubusercontent.com/tremby/imgur.sh/main/imgur.sh
        dest: ~/bin/imgur
        mode: '0775'

    - name: Install xrectsel tool
      copy:
        src: bin/xrectsel/xrectsel
        dest: ~/bin/
        owner: scott
        group: scott
        mode: '0775'

    - name: Install WeeChat scripts
      shell: |
        weechat-headless -a \
        --stdout \
        -r '/script install vimode.py' \
        -r '/script install go.py' \
        -r '/script install urlselect.lua' \
        -r '/wait 3 /quit'

  become_user: scott
