- name: Add PPA repo for peek tool
  apt_repository:
    repo: ppa:peek-developers/stable

- name: Install packages
  package:
    name:
      - git
      - stow
      - zsh
      - default-jdk
      - ruby
      - tmux
      - vim
      - xorg
      - i3
      - xbindkeys
      - xsel
      - xcompmgr
      - rxvt-unicode
      - chromium-browser
      - ansible
      - docker.io
      - alsa
      - pulseaudio
      - npm
      - vagrant
      - flameshot
      - peek
      - dbus-x11
      - libnotify-bin

- name: Install snap packages
  snap:
    classic: yes
    name:
      - intellij-idea-ultimate
      - webstorm

# TODO: Not working
#- name: Install gem packages
#  gem:
#    name: tmuxinator

- name: Install terraform
  become: yes
  shell: |
    curl https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip -o /tmp/terraform.zip && \
    unzip -d /usr/local/bin /tmp/terraform.zip && \
    rm /tmp/terraform.zip
  args:
    creates: /usr/local/bin/terraform
