dependencies:
  - role: common
    vars:
      user_groups: sudo
      install_packages:
        - zsh
        - tmux
        - vim
      user_files:
        - src: ssh/id_rsa
          dest: /home/scott/.ssh/
          mode: "0600"
        - src: ssh/known_hosts
          dest: /home/scott/.ssh/
          mode: "0644"
