- name: Add APT repositories
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: [deb]
    uris: "{{ item.uris }}"
    signed_by: "{{ item.signed_by }}"
    suites: [stable]
    components: [main]
    state: present
    enabled: true

- name: Update repositories cache
  ansible.builtin.apt:
    update_cache: true
