- name: Install packages required to set up dotfiles (i.e. git and stow)
  package:
    name:
      - git
      - stow

- name: Run all tasks as user
  block:
    - name: Clone dotfiles
      git:
        repo: git@github.com:ScottG489/dotfiles.git
        dest: /home/scott/.dotfiles
        update: no

    - name: Back up .bashrc
      copy:
        force: no
        remote_src: True
        src: /home/scott/.bashrc
        dest: /home/scott/.bashrc.bkp
    - name: Remove original .bashrc file
      file: path=/home/scott/.bashrc state=absent

    - name: Back up .zshrc
      copy:
        force: no
        remote_src: True
        src: /home/scott/.zshrc
        dest: /home/scott/.zshrc.bkp
    - name: Remove original .zshrc file
      file: path=/home/scott/.zshrc state=absent

    - name: Set up all dotfiles
      shell: /usr/bin/stow -S *
      args:
        chdir: /home/scott/.dotfiles

  become_user: scott
