- name: Import package install tasks
  import_tasks: package-install-tasks.yml

- name: Import user setup tasks
  import_tasks: user-setup-tasks.yml

- name: Import dotfile setup tasks
  import_tasks: dotfile-setup-tasks.yml

- name: Import vim plugin tasks
  import_tasks: vim-plugin-tasks.yml
