- name: Setup user
  user:
    name: scott
    groups: "{{ user_groups }}"
    shell: /bin/zsh

- name: Run all tasks as user
  block:
    - name: Create home bin dir
      file:
        path: /home/scott/bin
        state: directory
        owner: scott
        group: scott

    - name: Copy user files (i.e. secrets or files for boostrapping)
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"  # Trailing slash needed to create dirs if they don't exist
        owner: scott
        group: scott
        mode: "{{ item.mode }}"
      with_items: "{{ user_files }}"

    - name: Install oh-my-zsh
      # Reading in 'y' is necessary otherwise provisioning freezes. This is because the install script prompts 'y/n' at one point.
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" << EOF
        y
        EOF
      args:
        chdir: /home/scott/
        creates: ~/.oh-my-zsh

    - name: Clone tmux package manager (tpm)
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm

  become_user: scott
