- name: Setup user
  user:
    name: scott
    groups: "{{ user_groups }}"
    shell: /bin/zsh

- name: Create home bin dir
  become: yes
  become_user: scott
  file:
    path: ~/bin
    state: directory

- name: Copy user files (i.e. secrets or files for boostrapping)
  become: yes
  become_user: scott
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"  # Trailing slash needed to create dirs if they don't exist
    owner: scott
    group: scott
    mode: "{{ item.mode }}"
  with_items: "{{ user_files }}"

- name: Install oh-my-zsh
  become: yes
  become_user: scott
  # Reading in 'y' is necessary otherwise provisioning freezes. This is because the install script prompts 'y/n' at one point.
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" << EOF
    y
    EOF
  args:
    chdir: /home/scott/
    creates: ~/.oh-my-zsh

- name: Clone tmux package manager (tpm)
  become: yes
  become_user: scott
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
