- name: Install packages required to set up vim (i.e. git and vim)
  package:
    name:
      - git
      - vim

- name: Run all tasks as user
  block:
    - name: Clone vundle
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: /home/scott/.vim/bundle/Vundle.vim

    - name: Clone vim-airline
      git:
        repo: https://github.com/bling/vim-airline.git
        dest: /home/scott/.vim/bundle/vim-airline

    - name: Clone vim-colors-solarized
      git:
        repo: https://github.com/altercation/vim-colors-solarized.git
        dest: /home/scott/.vim/bundle/vim-colors-solarized

    - name: Clone vim-easymotion
      git:
        repo: https://github.com/Lokaltog/vim-easymotion.git
        dest: /home/scott/.vim/bundle/vim-easymotion

    - name: Clone vim-futigive
      git:
        repo: https://github.com/tpope/vim-fugitive.git
        dest: /home/scott/.vim/bundle/vim-fugitive

    - name: Clone vim-sensible
      git:
        repo: https://github.com/tpope/vim-sensible.git
        dest: /home/scott/.vim/bundle/vim-sensible

    - name: Install vundle plugins
      shell: |
        vim +PluginInstall +qall

  become_user: scott
