Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "scott-vm"
  config.disksize.size = '30GB'

  config.vm.define "windows" do |win|
    win.vm.provider "virtualbox" do |v|
      v.cpus = 4
      v.memory = 8000
    end

    win.vm.provision "ansible" do |ansible|
      ansible.playbook = "main-windows.yml"
      ansible.inventory_path = ".vagrant/provisioners/ansible/inventory"
    end
  end

  config.vm.define "mac" do |mac|
    mac.vm.provider "parallels" do |v|
      v.cpus = 4
      v.memory = 8000
    end

    mac.vm.provision "ansible" do |ansible|
      ansible.playbook = "main-mac.yml"
    end
  end

end
