Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/artful64"
  config.vm.hostname = "scott-vm"
  config.disksize.size = '30GB'
  config.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 4000
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main.yml"
  end

end
