- name: Add user to vboxusers group
  user:
    name: scott
    groups: "vboxusers"
    append: yes

- name: Reset SSH connection to allow VBox to discover USB devices and for group changes to apply
  meta: reset_connection

- name: Run tasks as user
  block:
    - name: Check if HAOS VM has already been set up
      shell: vboxmanage list vms | grep haos-vm
      register: create_haos_vm_result
      ignore_errors: true

    - name: Set up HAOS VM
      script: files/create-haos-vm.sh {{ haos_vm_memory_mb }}
      when: create_haos_vm_result is failed

  become_user: scott

- name: Copy service file for service to manage HAOS VM
  copy:
    src: vbox/haos-vm.service
    dest: /etc/systemd/system/haos-vm.service

- name: Enable service to manage HAOS VM
  ansible.builtin.systemd:
    name: haos-vm
    state: started
    enabled: yes
    daemon_reload: yes

- name: Copy script for service to persist wake on LAN
  copy:
    src: bin/persist-wol/persist-wol.sh
    dest: /usr/local/bin/persist-wol.sh
    mode: '0775'

- name: Copy service file for service to persist wake on LAN
  copy:
    src: wakeonlan/persist-wol.service
    dest: /etc/systemd/system/persist-wol.service

- name: Enable WOL persist service
  ansible.builtin.systemd:
    name: persist-wol
    state: started
    enabled: yes
    daemon_reload: yes
